[package]
name = "tquery"
version = "0.1.0"
authors = ["Skyward"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
nom = "6.2.1"
